version: "3"
services:
  web:
    image: 'php:7-fpm'
    working_dir: /var/www
    volumes: 
      - ./src:/src
    networks:
      - db-network
      - app-network
    container_name: php-app  
  proxy:
    image: nginx:alpine
    volumes: 
      - ./proxy/:/etc/nginx/conf.d/
      - ./src:/src
    networks:
      - app-network
    container_name: nginx-proxy
    ports: 
      - "8080:80"
  datasource:
    image: 'mysql:8'
    restart: unless-stopped
    environment: 
      MYSQL_ROOT_PASSWORD: "db_root_pass"
      MYSQL_DATABASE: "db_name"
      MYSQL_USER: "db_user"
      MYSQL_PASSWORD: "db_pass"
    networks:
      - db-network
    container_name: mysql-db
networks:
  db-network:
    driver: bridge
  app-network:
    driver: bridge